# -*- coding: utf-8 -*-
"""TCA(customer_chgurn_analysis).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DzQkIFoH8ogovkYt4qGy_S4taCsrEau8
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df = pd.read_csv("/content/Customer Churn.csv")

df.head()

df.tail()

df.info()

df.isnull().sum()

"""**Replacing blank with 0 as tenure is 0 and no total charges are recorded**"""

df["TotalCharges"] = df["TotalCharges"].replace(" ","0")
df["TotalCharges"] = df["TotalCharges"].astype("float")

df.info()

df.shape

df.describe()

df.duplicated().sum()

df["customerID"].duplicated().sum()

"""Converted 0 and 1 value of senior citizen to yes/no to make it easier to understand"""

def conv(value):
  if value == 1:
    return "yes"
  else:
    return "no"

df["SeniorCitizen"] = df["SeniorCitizen"].apply(conv)

df.head(10)

ax  = sns.countplot(x = df["Churn"] ,data = df)

ax.bar_label(ax.containers[0])
plt.title("Count of Customers by Churn")
plt.show()

gb = df.groupby("Churn").agg({"Churn":"count"})
gb
plt.pie(gb["Churn"],labels = gb.index, autopct = "%1.2f%%" )
plt.title("Percentage Of Churned Customers")
plt.show()

"""From the given pie chart we can conclude that 26.54% of our customers have churned out. lets's explore the reason behind it"""

#second option to do above one
df["Churn"].value_counts()

sns.countplot(x = "gender", data=df, hue = "Churn")
plt.title("Churn by Gender")
plt.show()

sns.countplot(x = "SeniorCitizen", data=df, hue = "Churn")
plt.title("Churn by Gender")
plt.show()

ax = sns.countplot(x = "SeniorCitizen", data=df,)
plt.title("Count of Customers by SeniorCitizenr")
ax.bar_label(ax.containers[0])
plt.show()

# Create grouped data in percentage
gb = df.groupby(["SeniorCitizen","Churn"]).size().unstack()
gb_percent = gb.div(gb.sum(axis=1), axis=0) * 100

# Plot stacked bar chart
ax = gb_percent.plot(kind="bar", stacked=True)

# Add percentage labels
for container in ax.containers:
    labels = [f"{v:.1f}%" if v > 0 else "" for v in container.datavalues]
    ax.bar_label(container, labels=labels, label_type="center")

plt.title("Churn Percentage by Senior Citizen")
plt.xlabel("Senior Citizen")
plt.ylabel("Percentage")

plt.show()

"""**Comparative a greated percentage of people in senior citizen category have churned**"""

sns.histplot(x = "tenure",data = df, bins = 72,hue="Churn")
plt.show()

"""**People who have use our services for long term have stayed and people who have used our services for 1 or 2 months have churned**"""

ax = sns.countplot(x = "Contract", data=df, hue="Churn")
ax.bar_label(ax.containers[0])
plt.title("Count of Customers by Contract")
plt.show()

"""**People who have contract of month to month contract have likely to churn than those who have 1 or 2 years of contract**



"""

df.columns.values

columns = [
    'PhoneService', 'MultipleLines', 'InternetService',
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies'
]

# create subplot grid
fig, axes = plt.subplots(3, 3, figsize=(18, 12))

# flatten axes for easier looping
axes = axes.flatten()

for i, col in enumerate(columns):
    sns.countplot(x=col, data=df, hue="Churn", ax=axes[i])
    axes[i].set_title(f"Churn by {col}")
    axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""**The majority of customerss who do not churn tend to have servies like PhoneServices,InternetService(particularly DSL) and OnlineSecurity enabled.For servies like OnlineBackup, TechSupport, and StreamingTV, churn rates are noticeably higher when these services are not used or are unavailable.**"""

plt.figure(figsize=(10,6))
ax = sns.countplot(x = "PaymentMethod", data=df, hue="Churn")
ax.bar_label(ax.containers[0])
ax.bar_label(ax.containers[1])
plt.title("Count of Customers by Payment Method")
plt.show()

"""**Customers is likely to churn when he is using electronic check as a payment method**"""

